services:
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    env_file:
      - ./order-service/.env
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - redis
      - eureka-server
    networks:
      - backend
      - messaging

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    env_file:
      - ./notification-service/.env
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - eureka-server
    networks:
      - backend
      - messaging

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    env_file:
      - ./user-service/.env
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - messaging

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - messaging

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  api-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - order-service
      - notification-service
      - user-service
      - eureka-server
    networks:
      - backend

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend

volumes:
  redis_data:

networks:
  backend:
    driver: bridge
  messaging:
    driver: bridge
