services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - ./order-service/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - orbit-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    env_file:
      - ./order-service/.env
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - orbit-network

volumes:
  postgres_data:

networks:
  orbit-network:
    driver: bridge
