server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service:8081
          predicates:
            - Path=/orders/**
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/api/users/**
        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - Path=/api/notifications/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false